#!/usr/bin/python3


#this file is for tesing only
#should be removed at a future date.

from SyntacticTypes import *
a = Atom()
print(a.parent())
o = OrEntailment()
print(o.parent())
arb = Arbitrary()
print(arb.parent())
t = Term()
print(t.parent())
